### PR TITLE
Windows

### PR DESCRIPTION
**Pull request by LuisTbx**
Hi, I have work a little to make the code compile and run under windows 10 with Cuda 10 and Visual Studio. Would you mind having a look to it? Best, Luis

### CODE REVIEW

**Comment by LuisTbx** [comment]
Missing pycocotools dependencies.

**Comment by kentaroy47** [comment]
windows support would be helpful.
should open up a new branch though.

**Comment by SJie1997** [comment]
Hello, you can give a complete tutorial about compiling this project to windows system

**Comment by SJie1997** [comment]
Hello, you can give a complete tutorial about compiling this project to windows system.Thank you very much!

**Comment by LuisTbx** [comment]
Hi, you can have a look to my clone of this repo. On the windows branch.
Hope it helps. I only made sure it works for inference, didn't test the
training.

Best, Luis.

**Comment by SJie1997** [comment]
Thank you very much, the model you mentioned is compilable and useful.

**Comment by JXMss** [comment]
@LuisTbx It will make a error:

> $ python setup.py build develop
running build
running build_py
running build_ext
building 'model._C' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -IG:\GP\faster-rcnn.pytorch\lib\model\csrc -ID:\ProgramData\Anaconda3\envs\pytorchFRCNN\lib\site-packages\torch\lib\include -ID:\ProgramData\Anaconda3\envs\pytorchFRCNN\lib\site-packages\torch\lib\include\TH -ID:\ProgramData\Anaconda3\envs\pytorchFRCNN\lib\site-packages\torch\lib\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" -ID:\ProgramData\Anaconda3\envs\pytorchFRCNN\include -ID:\ProgramData\Anaconda3\envs\pytorchFRCNN\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /TpG:\GP\faster-rcnn.pytorch\lib\model\csrc\vision.cpp /Fobuild\temp.win-amd64-3.6\Release\GP\faster-rcnn.pytorch\lib\model\csrc\vision.obj /MD -DTORCH_EXTENSION_NAME=model._C
vision.cpp
g:\gp\faster-rcnn.pytorch\lib\model\csrc\cpu/vision.h(3): fatal error C1083: ▒޷▒▒򿪰▒▒▒▒ļ▒: ▒▒torch/extension.h▒▒: No such file or directory
D:\ProgramData\Anaconda3\envs\pytorchFRCNN\lib\site-packages\torch\utils\cpp_extension.py:80: UserWarning: Error checking compiler version: [WinError 2] ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒
  warnings.warn('Error checking compiler version: {}'.format(error))
D:\ProgramData\Anaconda3\envs\pytorchFRCNN\lib\site-packages\torch\utils\cpp_extension.py:106: UserWarning:

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (cl) may be ABI-incompatible with PyTorch!
Please use a compiler that is ABI-compatible with GCC 4.9 and above.
See https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html.

See https://gist.github.com/goldsborough/d466f43e8ffc948ff92de7486c5216d6
for instructions on how to install GCC 4.9 or higher.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(ABI_INCOMPATIBILITY_WARNING.format(compiler))
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

**Comment by JXMss** [comment]
@LuisTbx i have no idea how to solve it.
Any assistance rendered me would be highly appreciated.

**Comment by LuisTbx** [comment]
Hi did you get the checkout of the windows branch?

Did you follow the installation instructions for PyCoCo?

I moved to the Pytorch official maskrcnn implementation, its way easier to
get it up and running.

Best,

**Comment by JXMss** [comment]
@LuisTbx yeah, i get the windows branch and pycocotool
and i have gcc 6.3.0(by MinGW) and VS2017 compiler
would u mind giving me a website?

**Comment by JXMss** [comment]
in fact, i need a pytorch Faster RCNN to write my paper, but it's hard to find a runnable project=<

**Comment by LuisTbx** [comment]
That is the secret! You need to compile using VS (CL) Look for the line
about setting vcvarsall in x64 mode.

If you wanna give a try to the PyTorch official maskrcnn (frcnn) check the
tutorials in

https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html

Hope it helps.

**Comment by JXMss** [comment]
when i use the vs2017 x86_x64 or x64_x86 prompt, it will make another error:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
(the prompt dont allow copying)
and thx for ur link=)

**Comment by LuisTbx** [comment]
I used the native CMD from windows. To compile. And only used it for the
inference, so no training...

The PyTorch frcnn is very easy to use. The hardest part would be creating
the dataloader. Try having a look on how it is done in the example, it
should be straight forward to implement your own.

Best,

**Comment by JXMss** [comment]
but i cant compile the cuda dependencies, how miserable! T_T

**Comment by LeezPayne** [comment]
It does work，thank you！

**Pull request closed without merging**
